"""Generate fix proposals from analyses using the configured AI agent."""

from __future__ import annotations

from typing import Any, Dict

from src.ai_agent import HybridAgent
from src.models.fix_proposal import FixProposal, FileChange


class FixGenerator:
    """Create structured fix proposals from analysis results."""

    def __init__(self) -> None:
        self.agent = HybridAgent()

    async def generate_fix(
        self,
        analysis_id: str,
        error_analysis: Dict[str, Any],
        code_context: str,
    ) -> FixProposal:
        """Generate a fix proposal using Bob/OpenAI."""
        fix_data = await self.agent.generate_fix(error_analysis, code_context)

        # Extract file_path from analysis or fix_data
        file_path = (
            error_analysis.get("file_path") or
            fix_data.get("file_path") or
            ""
        )

        # Handle multiple file changes if provided
        file_changes = []
        raw_file_changes = fix_data.get("file_changes", [])
        
        if raw_file_changes:
            # AI provided multiple file changes
            for change in raw_file_changes:
                file_changes.append(FileChange(
                    file_path=change.get("file_path", ""),
                    original_code=change.get("original_code", ""),
                    fixed_code=change.get("fixed_code", "")
                ))
        elif fix_data.get("fixed_code"):
            # Single file change (backward compatibility)
            file_changes.append(FileChange(
                file_path=file_path,
                original_code=fix_data.get("original_code", ""),
                fixed_code=fix_data.get("fixed_code", "")
            ))

        return FixProposal(
            analysis_id=analysis_id,
            file_path=file_path,
            file_changes=file_changes,
            original_code=fix_data.get("original_code", ""),
            fixed_code=fix_data.get("fixed_code", ""),
            explanation=fix_data.get("explanation", "No explanation provided"),
            commit_message=fix_data.get("commit_message", f"Fix issue for {analysis_id}"),
            pr_description=fix_data.get("pr_description", "Automated fix generated by AutoFix System"),
            test_suggestions=fix_data.get("test_suggestions", []),
        )


# Made with Bob