"""Main entry point for Fixium documentation analysis."""
import sys
import json
from pathlib import Path
from typing import NoReturn
from datetime import datetime

from .config import Config
from .comment_parser import CommentParser
from .github_client import GitHubClient
from .access_control import AccessControl
from .progress_tracker import ProgressTracker
from .doc_runner import DocRunner
from .error_handler import ErrorHandler


def format_doc_suggestions(results: dict) -> str:
    """
    Format documentation suggestions as markdown comment.
    
    Args:
        results: Analysis results dictionary
        
    Returns:
        Formatted markdown string
    """
    lines = ["## 📚 Documentation Analysis Results\n"]
    
    classification = results.get('changeClassification', {})
    lines.append(f"**Change Type**: {classification.get('type', 'unknown')}")
    lines.append(f"**Confidence**: {classification.get('confidence', 'unknown')}")
    
    reasons = classification.get('reasons', [])
    if reasons:
        lines.append(f"**Reasons**: {', '.join(reasons[:3])}")  # Show first 3 reasons
    
    lines.append("")
    
    if not results.get('shouldUpdateDocs', False):
        lines.append("✅ **No documentation updates needed**")
        lines.append("\nChanges are minor (bug fixes, dependency updates, etc.) and don't require documentation updates.")
        lines.append("\n---")
        lines.append("*🤖 Generated by Fixium Documentation Analyzer*")
        return "\n".join(lines)
    
    summary = results.get('summary', {})
    lines.append(f"**Documentation Files Analyzed**: {summary.get('totalDocsDiscovered', 0)}")
    lines.append(f"**Gaps Found**: {summary.get('totalGaps', 0)}\n")
    
    gaps = results.get('documentationGaps', [])
    if gaps:
        lines.append("### 📝 Suggested Updates\n")
        
        # Group by priority
        by_priority = {'critical': [], 'high': [], 'medium': [], 'low': []}
        for gap in gaps:
            priority = gap.get('priority', 'low')
            by_priority[priority].append(gap)
        
        # Show critical and high priority first
        for priority in ['critical', 'high', 'medium', 'low']:
            priority_gaps = by_priority[priority]
            if not priority_gaps:
                continue
            
            priority_emoji = {
                'critical': '🔴',
                'high': '🟡',
                'medium': '🔵',
                'low': '⚪'
            }.get(priority, '⚪')
            
            for gap in priority_gaps:
                lines.append(f"#### {priority_emoji} {gap.get('file', 'Unknown')} - {gap.get('section', 'Unknown')}")
                lines.append(f"**Priority**: {priority.upper()}")
                lines.append(f"**Issue**: {gap.get('issue', 'No description')}")
                lines.append(f"**Suggestion**: {gap.get('suggestion', 'No suggestion')}")
                
                example = gap.get('exampleContent', '')
                if example:
                    lines.append(f"\n**Example Content**:")
                    lines.append(f"```markdown\n{example}\n```")
                
                related = gap.get('relatedChanges', [])
                if related:
                    lines.append(f"**Related Changes**: {', '.join(related[:3])}")
                
                lines.append("")
    
    # Show files that were checked but are OK
    checked_ok = results.get('filesCheckedNoGaps', [])
    if checked_ok:
        lines.append("\n### ✅ Files Checked (No Updates Needed)\n")
        for item in checked_ok[:5]:  # Show first 5
            lines.append(f"- **{item.get('file', 'Unknown')}**: {item.get('reason', 'OK')}")
    
    lines.append("\n---")
    lines.append("*🤖 Generated by Fixium Documentation Analyzer*")
    
    return "\n".join(lines)


def exit_with_error(message: str, code: int = 1) -> NoReturn:
    """
    Print error message and exit.
    
    Args:
        message: Error message
        code: Exit code
    """
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(code)


def main() -> None:
    """Documentation analysis workflow orchestrator."""
    print("📚 Fixium Documentation Analyzer - Starting...")
    
    # Load configuration
    config = Config()
    
    # Validate configuration
    config_errors = config.validate()
    if config_errors:
        error_msg = "Configuration validation failed:\n" + "\n".join(f"  - {e}" for e in config_errors)
        exit_with_error(error_msg)
    
    print(f"✓ Configuration loaded: {config}")
    
    # Initialize components
    try:
        github_client = GitHubClient(config.github_token, config.github_repository)
        print(f"✓ GitHub client initialized for {config.github_repository}")
    except Exception as e:
        exit_with_error(f"Failed to initialize GitHub client: {e}")
    
    access_control = AccessControl(config.authorized_users)
    error_handler = ErrorHandler(github_client, config.pr_number)
    
    try:
        # Parse command
        print(f"Parsing comment: {config.comment_body[:100]}...")
        command = CommentParser.parse(config.comment_body)
        
        if not command or command.command != 'updatedocs':
            print("✗ Invalid command for doc analysis")
            error_handler.handle_invalid_command(config.comment_body)
            sys.exit(1)
        
        print(f"✓ Command parsed: {command.command}")
        print(f"  Options: {command.doc_options}")
        
        # Check authorization
        print(f"Checking authorization for user: {config.comment_user}")
        if not access_control.is_authorized(config.comment_user):
            print(f"✗ User {config.comment_user} is not authorized")
            message = access_control.get_unauthorized_message(config.comment_user)
            github_client.post_comment(config.pr_number, message)
            sys.exit(1)
        
        print(f"✓ User {config.comment_user} is authorized")
        
        # Start progress tracking
        progress = ProgressTracker(github_client, config.pr_number)
        options_info = str(command.doc_options)
        comment_id = progress.start(f"Analyzing documentation gaps... {options_info}")
        print(f"✓ Progress tracking started (comment ID: {comment_id})")
        
        # Get PR information
        print("Fetching PR information...")
        progress.update("Fetching PR information...", "Getting changed files and commits")
        
        try:
            pr_files = github_client.get_pr_files(config.pr_number)
            pr = github_client.get_pull_request(config.pr_number)
            pr_title = pr.title
            
            # Get commit messages (simplified - get from PR commits)
            commits = list(pr.get_commits())
            commit_messages = [c.commit.message for c in commits]
            
            print(f"✓ PR info: {len(pr_files)} files, {len(commit_messages)} commits")
        except Exception as e:
            print(f"✗ Failed to fetch PR info: {e}")
            error_handler.handle_unexpected_error(f"Failed to fetch PR info: {e}", progress)
            sys.exit(1)
        
        # Run documentation analysis
        print("Running documentation gap analysis...")
        progress.update("Analyzing documentation...", "Checking all .md files for gaps")
        
        doc_runner = DocRunner(config.workspace_dir)
        output_file = f"docs_analysis_pr{config.pr_number}.json"
        
        # Check if scripts exist
        scripts_status = doc_runner.check_scripts_exist()
        print(f"  Scripts status: {scripts_status}")
        
        if not all(scripts_status.values()):
            missing = [name for name, exists in scripts_status.items() if not exists]
            error_msg = f"Required scripts not found: {', '.join(missing)}"
            print(f"✗ {error_msg}")
            error_handler.handle_unexpected_error(error_msg, progress)
            sys.exit(1)
        
        try:
            results = doc_runner.analyze_pr_docs(
                pr_number=config.pr_number,
                pr_files=pr_files,
                commit_messages=commit_messages,
                pr_title=pr_title,
                output_file=output_file,
                skip_classification=command.doc_options.skip_classification
            )
            print(f"✓ Analysis completed")
        except TimeoutError as e:
            print(f"✗ Analysis timeout: {e}")
            error_handler.handle_timeout(progress)
            sys.exit(1)
        except RuntimeError as e:
            print(f"✗ Analysis error: {e}")
            error_handler.handle_unexpected_error(str(e), progress)
            sys.exit(1)
        
        # Save results to file
        output_path = Path(config.workspace_dir) / output_file
        with open(output_path, 'w') as f:
            json.dump(results, f, indent=2)
        print(f"✓ Results saved to {output_file}")
        
        total_gaps = results.get('summary', {}).get('totalGaps', 0)
        should_update = results.get('shouldUpdateDocs', False)
        
        print(f"✓ Should update docs: {should_update}")
        print(f"✓ Total gaps found: {total_gaps}")
        
        # Format and post comment
        print("Posting results to PR...")
        progress.update("Posting results...", "Formatting and submitting comment")
        
        comment = format_doc_suggestions(results)
        github_client.post_comment(config.pr_number, comment)
        print("✓ Results posted to PR")
        
        # Complete progress
        if should_update:
            summary = f"{total_gaps} documentation gap(s) found"
        else:
            summary = "No documentation updates needed (minor changes)"
        
        progress.complete(total_gaps, summary)
        print("✅ Fixium documentation analysis completed successfully!")
        
    except KeyboardInterrupt:
        print("\n✗ Analysis interrupted by user")
        sys.exit(130)
    except Exception as e:
        print(f"✗ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        error_handler.handle_unexpected_error(str(e))
        sys.exit(1)


if __name__ == '__main__':
    main()


# Made with Bob